### ISSUE TITLE
Support for character like T̈ ẗ in bold mode

### ISSUE THREAD

**Issue by msrosyidi** [khaledhosny/libertine#7]
Is there any plan to support this character T̈ ẗ like in DejaVu Serif?
![screenshot_20151029093243](https://cloud.githubusercontent.com/assets/3489885/10808624/2c5f41c6-7e20-11e5-9f39-9d0397523e70.png)

Also is there bold and italic mode for Libertine Mono?

Thanks.

**Comment by khaledhosny** [comment]
The accent issue should be fixed now. No plans for extending the mono family (I don’t like it personally, there are many better mono fonts).

**Comment by msrosyidi** [comment]
Thanks.

**Comment by msrosyidi** [comment]
Using MS Word I get those characters as I need but how to get those using xelatex and fontspec? I still get like this:
![screenshot_20151029190321](https://cloud.githubusercontent.com/assets/3489885/10817896/c05fbf46-7e6f-11e5-94da-7b31421f1a45.png)

**Comment by khaledhosny** [comment]
Can you show me you TeX document?

**Comment by msrosyidi** [comment]
I cannot attach the file here. This my TeX document:
```tex
\documentclass[a4paper,12pt]{article}
\usepackage[no-math,quiet]{fontspec}
\setmainfont[Ligatures=TeX]{Libertine Serif}
\setsansfont[Ligatures=TeX,Scale=MatchLowercase]{Libertine Sans}
\setmonofont[Scale=MatchLowercase]{Libertine Mono}
\newfontfamily\arabicfont[Script=Arabic,Mapping=arabicdigits]{Amiri}
\usepackage[quiet]{polyglossia}
\setmainlanguage{bahasai}
\setotherlanguage{arabic}
\begin{document}

{\"H {\bfseries \"H} {\itshape \"H} {\itshape\bfseries \"H}  {\slshape \"H} {\slshape\bfseries \"H}

 \"h {\bfseries \"h} {\itshape \"h} {\itshape\bfseries \"h}  {\slshape \"h} {\slshape\bfseries \"h}

 \"T {\bfseries \"T} {\itshape \"T} {\itshape\bfseries \"T}  {\slshape \"T} {\slshape\bfseries \"T}

 \"t {\bfseries \"t} {\itshape \"t} {\itshape\bfseries \"t}  {\slshape \"t} {\slshape\bfseries \"t}}

{\scshape\"H {\bfseries \"H} {\itshape \"H} {\itshape\bfseries \"H}  {\slshape \"H} {\slshape\bfseries \"H}

				 \"h {\bfseries \"h} {\itshape \"h} {\itshape\bfseries \"h}  {\slshape \"h} {\slshape\bfseries \"h}

				 \"T {\bfseries \"T} {\itshape \"T} {\itshape\bfseries \"T}  {\slshape \"T} {\slshape\bfseries \"T}

         \"t {\bfseries \"t} {\itshape \"t} {\itshape\bfseries \"t}  {\slshape \"t} {\slshape\bfseries \"t}}

{Ḧḧ T̈ẗ} {\bfseries Ḧḧ T̈ẗ} {\itshape Ḧḧ T̈ẗ} {\itshape\bfseries Ḧḧ T̈ẗ} {\slshape Ḧḧ T̈ẗ} {\slshape\bfseries Ḧḧ T̈ẗ}
 				 
{Ḧḧ T̈ẗ} {\bfseries Ḧḧ T̈ẗ} {\itshape Ḧḧ T̈ẗ} {\bfseries\itshape Ḧḧ T̈ẗ} {\slshape Ḧḧ T̈ẗ} {\bfseries\slshape Ḧḧ T̈ẗ}

\end{document}
```
and I generated the pdf file using XeLaTeX.

**Comment by khaledhosny** [comment]
I renders as expected here (using TeX Live 2015), so I guess it is something on your end. Try removing the fonts completely then reinstalling them, sometimes Windows keep the old version of the font when you install a new version.

**Comment by msrosyidi** [comment]
Oh, so it is about windows.
After reinstalling the new font and running xelatex I see in the log file there are strange things like this:
```tex
...
 -> .../Windows/Fonts/libertineserif-semibold_2.otf
...
```
there is number added to name of the font files but I cannot find those file in windows font directory. I try to search using a searching software and deleted them from it. Installing again the new font, running xelatex again and I get those character as I need but when I open the pdf file using Adobe Acrobat XI and also Adobe Reader XI there is a warning like this:
![screenshot_20151030004206](https://cloud.githubusercontent.com/assets/3489885/10827254/7a249a3e-7ea0-11e5-88d0-f4de863662be.png)
But I do not get this warning when I open it using SumatraPDF and Evince.

**Comment by khaledhosny** [comment]
>  -> .../Windows/Fonts/libertineserif-semibold_2.otf

Yes, that is the Windows issue. When installing a font that already
exists, instead of replacing the old files, Windows renames them. So
when installing new version of existing fonts on Windows, I always
remove the old ones first.

> when I open the pdf file using Adobe Acrobat XI and also Adobe Reader
> XI there is a warning like this:

No idea about this warning, I see nothing suspicious in the font.

**Comment by msrosyidi** [comment]
Thanks.
